### ISSUE TITLE
亲爱的佬     云编译一直报错可以看看不

### ISSUE THREAD

**Issue by f0yu** [windowsair/wireless-esp8266-dap#62]
Run git clone https://github.com/espressif/esptool.git
Cloning into 'esptool'...
Traceback (most recent call last):
  File "./esptool/esptool.py", line 34, in <module>
    import esptool
  File "/home/runner/work/wireless-esp32c3-dap/wireless-esp32c3-dap/esptool/esptool/__init__.py", line 41, in <module>
    from esptool.bin_image import intel_hex_to_bin
  File "/home/runner/work/wireless-esp32c3-dap/wireless-esp32c3-dap/esptool/esptool/bin_image.py", line [16](https://github.com/f0yu/wireless-esp32c3-dap/actions/runs/6761635384/job/18376702546#step:7:17), in <module>
    from intelhex import IntelHex
ModuleNotFoundError: No module named 'intelhex'
Error: Process completed with exit code 1.

**Comment by windowsair** [comment]
我修下CI

**Comment by f0yu** [comment]
好像是这个esptool被更新了    新引入一个东西    要用以前的版本    
奈何我水平太菜  ....

**Comment by windowsair** [comment]
可以试下这个版本
https://github.com/windowsair/wireless-esp8266-dap/commit/687e9531b88f42afe0966a6be9e0b77cac1ccf73
